### ISSUE TITLE
Screen Shots

### ISSUE THREAD

**Issue by TheCodeTraveler** [TheCodeTraveler/GitHubXamarin#2]
![GitHubXamarin](https://user-images.githubusercontent.com/13558917/55269270-c8791b80-5267-11e9-8375-3d54651f3a35.gif)

**Comment by brminnick** [comment]
![GitHubXamarin](https://user-images.githubusercontent.com/13558917/55269310-358cb100-5268-11e9-8ff0-41dee7d10042.gif)

**Comment by brminnick** [comment]
<img width="486" alt="Screen Shot 2019-08-10 at 12 57 36 PM" src="https://user-images.githubusercontent.com/13558917/62826345-759d6200-bb7f-11e9-862a-6d03ea325d47.png">
<img width="469" alt="Screen Shot 2019-08-10 at 12 57 05 PM" src="https://user-images.githubusercontent.com/13558917/62826346-759d6200-bb7f-11e9-9da8-8de61844cbe3.png">

**Comment by brminnick** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/13558917/62826588-d6c73480-bb83-11e9-8536-ec67e32c5c82.gif)

**Comment by brminnick** [comment]
![ScreenFlow](https://user-images.githubusercontent.com/13558917/62826859-e432ed80-bb88-11e9-8418-3ce1cde2dd42.gif)
